# Rename this file to languages.toml to enable multilingual support
[pt-br]
languageName = "Português"
languagedirection = "ltr"
title = "Info☭Guerrilla"
weight = 1

[en]
languageName = "English"
languagedirection = "ltr"
title = "Info☭Guerrilla"
weight = 2

