# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/infoguerrilla/"

[social.params]
icon = "brand-github"

[[social]]
identifier = "X"
name = "X"
url = "#"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "xBluesky"
name = "Social-Bluesky"
url = "#"

[social.params]
icon = "brand-bluesky"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "#"

[social.params]
icon = "brand-instagram"

[[social]]
identifier = "rss"
name = "x-RSS Feed"
url = "https://infoguerrilla.github.io/index.xml"

[social.params]
icon = "rss"


